### ISSUE TITLE
Bug: Empty textEdit.newText in the response of the textDocument/completion method

### ISSUE THREAD

**Issue by darklam** [Kotlin/kotlin-lsp#105]
First of all many thanks for making this LSP happen; I've been waiting for this for years! ❤️ 

Now the issue is that the LSP returns a response for the textDocument/completion method with the newText always being an empty string and start/end being the same character. I think this breaks the completion in the Zed editor, so when trying to insert the completion nothing happens. In VS Code there might be different fallbacks for this case and it works.

Example response:
```javascript
"textEdit": {
            "newText": "",
            "insert": {
                "start": {
                    "line": 75,
                    "character": 15
                },
                "end": {
                    "line": 75,
                    "character": 15
                }
            },
            "replace": {
                "start": {
                    "line": 75,
                    "character": 15
                },
                "end": {
                    "line": 75,
                    "character": 15
                }
            }
        }
``` 

This seems to happen on purpose in the LSAbstractCompletionProvider where textEdit is set to emptyTextEdit().
https://github.com/Kotlin/kotlin-lsp/blob/17728b9f21b286ebf3076641fa48375bae4020dc/features-impl/common/src/com/jetbrains/ls/api/features/impl/common/completion/LSAbstractCompletionProvider.kt#L76
Perhaps this is to implement the first mode described in the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion), but in this case the textEdit should be omitted completely if I understand it correctly.

This might be a misunderstanding on my part and not an issue, as I don't really know much about the LSP specification, but I saw that there was this issue in Zed and not in VS Code and wanted to dig around to figure out why.

**Comment by itsramiel** [comment]
This is also messes up auto completion in neovim

https://github.com/user-attachments/assets/b98fbef1-4225-43de-89ff-38000b2fa2f5

**Comment by josuf107** [comment]
In case it helps anyone in nvim I patched the [completion.lua](https://github.com/neovim/neovim/blob/ff792f8e690854aaae9be627c583b596faf137c0/runtime/lua/vim/lsp/completion.lua#L193) script with

```
    local word = item.textEdit.newText
    local trimWhitespace = word:match('^(%S*)') or word     
    if trimWhitespace ~= '' then  
      return trimWhitespace       
    else                                                          
      return item.label                                       
    end 
```

Since `newText` is empty it returns the `item.label` which is the fallback in other cases. I'm not sure if this should be fixed in nvim or kotlin-lsp or both. It seems wrong to populate an empty `newText`, but there is a lot of fallback logic in completion.lua already.

**Comment by strangepleasures** [comment]
@darklam @itsramiel could you please check if the bug is still present in the latest release?

**Comment by kernitus** [comment]
> [@darklam](https://github.com/darklam) [@itsramiel](https://github.com/itsramiel) could you please check if the bug is still present in the latest release?

Most definitely. Using version `261.13587.0` it looks like `textEdit.newText` is empty and the actual completion is locked behind the `command`. I don't think that's how neovim-lsp expects an LSP to behave, as this works fine with e.g. Typescript and Python LSPs.

```
RESULT: { {
    command = {
      arguments = { 9019 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "Big5",
    labelDetails = {
      detail = " (sun.nio.cs)"
    },
    sortText = "0000000000",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
      arguments = { 9020 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "Big5_HKSCS",
    labelDetails = {
      detail = " (sun.nio.cs)"
    },
    sortText = "0000000001",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
      arguments = { 9021 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "Big5_HKSCS_2001",
    labelDetails = {
      detail = " (sun.nio.cs.ext)"
    },
    sortText = "0000000002",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
      arguments = { 9022 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "Big5_Solaris",
    labelDetails = {
      detail = " (sun.nio.cs.ext)"
    },
    sortText = "0000000003",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
      arguments = { 9023 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "BigDecimal",
    labelDetails = {
      detail = " (java.math)"
    },
    sortText = "0000000004",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
      arguments = { 9024 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 13,
    label = "BigDecimalLayoutForm",
    labelDetails = {
      detail = " (java.util.Formatter)"
    },
    sortText = "0000000005",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
     arguments = { 9025 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "BigDecimal",
    labelDetails = {
      detail = " (aws.smithy.kotlin.runtime.content)"
    },
    sortText = "0000000006",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
      arguments = { 9026 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "BigInteger",
    labelDetails = {
      detail = " (java.math)"
    },
    sortText = "0000000007",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
         line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
      arguments = { 9027 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "BigInteger",
    labelDetails = {
      detail = " (aws.smithy.kotlin.runtime.content)"
    },
    sortText = "0000000008",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  }, {
    command = {
      arguments = { 9028 },
      command = "jetbrains.kotlin.completion.apply",
     title = "Apply Completion"
    },
    data = {
      configurationEntryId = "KotlinCompletionProvider"
    },
    kind = 7,
    label = "BufferedImageGraphicsConfig",
    labelDetails = {
      detail = " (sun.awt.image)"
    },
    sortText = "0000000009",
    textEdit = {
      insert = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 14,
          line = 90
        },
        start = {
          character = 14,
          line = 90
        }
      }
    }
  } }
```

It is possible #82 is related.

**Comment by jpaju** [comment]
This also affects [Helix editor.](https://helix-editor.com/) When applying a completion, nothing is inserted because Helix applies the provided `textEdit` directly (which has empty string  in `newText`).

Agreeing with the analysis by author: per the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion), if the server expects clients to use the label for insertion text, `textEdit` should be omitted, and not provided with an empty string. The current behavior puts the burden on clients to implement non-standard fallback logic.

**Comment by marks0mmers** [comment]
@strangepleasures I checked and just wanted to let you know that this is still present in the latest version

**Comment by jpaju** [comment]
Did some further investigation on this and wanted to share findings.

## Current behavior

Each completion item in the response includes a `command` field alongside an empty `textEdit`:

```json
{
  "label": "foo",
  "textEdit": {
    "newText": "",
    "insert": { "start": { "line": 1, "character": 20 }, "end": { "line": 1, "character": 20 } },
    "replace": { "start": { "line": 1, "character": 20 }, "end": { "line": 1, "character": 20 } }
  },
  "command": {
    "title": "Apply Completion",
    "command": "jetbrains.kotlin.completion.apply",
    "arguments": [23]
  }
}
```

The flow this creates when a user accepts a completion:

1. User selects a completion item
2. Client applies the `textEdit` from the response, which inserts nothing since `newText` is empty (more on this below)
3. Client executes the `command` from the response via `workspace/executeCommand`
4. Server performs the actual text edit as a result of the command

This is the opposite of how completion is supposed to work: the server should provide the insertion text in the response and the client applies it locally, with no further server involvement needed.

## Why this is a problem

- Using `command` as the primary mechanism for text insertion is non-standard. Per the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem), commands are meant for optional side effects that happen after insertion, not the insertion itself.
- Completion is one of the most fundamental LSP operations and is supported by virtually every editor. Command execution is not, and many editors implement completion without supporting `CompletionItem.command`. Relying on `command` execution for something as basic as inserting text from completion severely limits the number of compatible editors.
- It requires an extra round trip to the server for every accepted completion, adding unnecessary latency.

## Suggested fixes

A completion item can provide insertion text in a few ways, in order of precedence:

1. `textEdit.newText` is used when `textEdit` is present, and the other options are ignored
2. `insertText` is used when no `textEdit` is provided
3. `label` is used as a last resort fallback

Since the current response includes a `textEdit` with an empty `newText`, nothing gets inserted and there is no fallback to `label`. Two standard approaches that would fix this:

**1. Populate `newText` with the actual insertion text:**

```json
{
  "label": "foo",
  "textEdit": {
    "newText": "foo",
    "insert": { "start": { "line": 1, "character": 20 }, "end": { "line": 1, "character": 20 } },
    "replace": { "start": { "line": 1, "character": 20 }, "end": { "line": 1, "character": 20 } }
  }
}
```

**2. Omit `textEdit` entirely so clients fall back to `label`:**

```json
{
  "label": "foo",
  "labelDetails": { }
}
```

**Comment by marks0mmers** [comment]
I have been using the new version for a couple of days and I want to say this has been resolved?

**Comment by jpaju** [comment]
Just checked the `CompletionItem` response from the newest Kotlin LSP version (262.7569.0), and it's not fixed. The response still includes empty `newText` and completion relies on client executing `jetbrains.kotlin.completion.apply` command

```json
{
  "label": "foo",
  "textEdit": {
    "newText": "",
    "insert": {
      "start": { ... },
      "end": { ... }
    }
  },
  "command": {
    "title": "Apply Completion",
    "command": "jetbrains.kotlin.completion.apply",
    "arguments": [...]
  }
}
```

**Comment by pianobyte** [comment]
I was debugging a different issue, where the cursor position after completion does not land into the correct position.   
But this also confirms the analysis of @jpaju highlighted in this thread.  
> Note: I will use `|` as the cursor position. 
# Test scenario 1
## Before completion
```kotlin
class Test {
    fun testFunction() {
        val testString: Str|
    }
}
```
## After completion
```kotlin
class Test {
    fun testFunction() {
        val testString: Strin|g
    }
}
```
## Lsp output
```json
{
  cursor_loc = { 6, 29 },
  cusor_loc_text = "        val testString: Strin|g",
  lsp_item = {
    client_id = 1,
    client_name = "kotlin",
    command = {
      arguments = { 1 },
      command = "jetbrains.kotlin.completion.apply",
      title = "Apply Completion"
    },
    cursor_column = 29,
    data = {
      KotlinCompletionItemKey = 1,
      configurationEntryId = "KotlinCompletionProvider"
    },
    exact = false,
    kind = 7,
    label = "String",
    labelDetails = {
      detail = " (kotlin)"
    },
    score = 92,
    score_offset = 0,
    sortText = "0000000000",
    source_id = "lsp",
    source_name = "LSP",
    textEdit = {
      insert = {
        ["end"] = {
          character = 29,
          line = 5
        },
        start = {
          character = 29,
          line = 5
        }
      },
      newText = "",
      replace = {
        ["end"] = {
          character = 29,
          line = 5
        },
        start = {
          character = 29,
          line = 5
        }
      }
    }
  }
}
```

# Test scenario 2 (OK Scenario)
## Before completion
```kotlin
class Test {
    fun testFunction() {
        val testString: List<String> = list|
    }
}
```
## After completion
```kotlin
class Test {
    fun testFunction() {
        val testString: List<String> = listOf(|)
    }
}
```
For this case, I think the cursor position lands into the correct place since I would expect to add parameter after the function completion.

**Comment by sharoha** [comment]
Hi @strangepleasures . Apologies for tagging you here again, but i think the problem still exists for this repo. It would be appreciated if you can comment on this.

**Comment by jjbavdb** [comment]
Hi all! Just want to share here that the issue still occurs on latest build.

I did manage to workaround it, thanks to Emacs. You can see the full fix for completions (and also for JAR navigation for 3rd party code go-to definition) in my heks-emacs config: https://codeberg.org/jjba23/heks-emacs/src/branch/trunk/src/modules/eglot.el

```emacs-lisp
  (defun my-jsonrpc-request-kotlin-fix (orig-fn connection method params &rest args)
    "Fix kotlin-lsp empty newText bug by removing textEdit to trigger Eglot fallback."
    (let ((result (apply orig-fn connection method params args)))
      (when (and (eq method :textDocument/completion)
                 (derived-mode-p 'kotlin-mode 'kotlin-ts-mode)
                 result)
        (let ((items (if (vectorp result) result (plist-get result :items))))
          (seq-do (lambda (item)
                    (let ((text-edit (plist-get item :textEdit)))
                      ;; If the server sent an empty newText, strip textEdit completely
                      ;; so Eglot falls back to replacing the actual prefix.
                      (when (and text-edit (equal (plist-get text-edit :newText) ""))
                        (plist-put item :textEdit nil))))
                  items)))
      result))

  (defun my-jsonrpc-async-request-kotlin-fix (orig-fn connection method params &rest args)
    "Fix kotlin-lsp empty newText bug in asynchronous Eglot requests."
    (if (and (eq method :textDocument/completion)
             (derived-mode-p 'kotlin-mode 'kotlin-ts-mode))
        (let* ((orig-success (plist-get args :success-fn))
               (new-success (lambda (result)
                              (let ((items (if (vectorp result) result (plist-get result :items))))
                                (seq-do (lambda (item)
                                          (let ((text-edit (plist-get item :textEdit)))
                                            (when (and text-edit (equal (plist-get text-edit :newText) ""))
                                              (plist-put item :textEdit nil))))
                                        items))
                              (funcall orig-success result)))
               (new-args (plist-put (copy-sequence args) :success-fn new-success)))
          (apply orig-fn connection method params new-args))
      (apply orig-fn connection method params args)))

  (advice-add 'jsonrpc-request :around #'my-jsonrpc-request-kotlin-fix)
  (advice-add 'jsonrpc-async-request :around #'my-jsonrpc-async-request-kotlin-fix)
```

**Comment by josuf107** [comment]
For neovim if you accept a completion with `<C-y>` rather than `<CR>` it seems to get the completion from the completion command. I think it's to do with buffer dirtying before the completion command commits if you press enter. This snippet makes enter work in the popup menu:

```
vim.keymap.set('i', '<CR>', function()
    return vim.fn.pumvisible() == 1 and '<C-y>' or '<CR>'
end, { expr = true })
```
